version: '2'
services:
  db:
    image: postgres
  # db_sql:
  #   image: library/mysql:5.6.22
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mypass
  #   ports:
  #     - "13306:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/server.pid
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    # depends_on:
    #   - db_sql
    